version: "3.4"
services: 
    database:
      container_name: "blog_database"
      build: "./database"
    server:
      container_name: "blog_server"
      build: "./server"
      ports:
        - 5000:5000